name: Electron Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  NODE_VERSION: '22.21.1'
  PNPM_VERSION: '10.15.1'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          cd electron
          pnpm install --frozen-lockfile

      - name: Build and Publish
        run: |
          cd electron
          pnpm run publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
